# Generated by Django 4.2.19 on 2025-02-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('occupation', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('bloog_group', models.CharField(max_length=3)),
                ('observations', models.TextField(blank=True, null=True)),
                ('id_socio', models.IntegerField()),
                ('teacher', models.BooleanField()),
            ],
        ),
    ]
